insert into mainapp_states (name, code) values('Alabama',  'AL');
insert into mainapp_states (name, code) values('Alaska',  'AK');
insert into mainapp_states (name, code) values('Arizona',  'AZ');
insert into mainapp_states (name, code) values('Arkansas',  'AR');
insert into mainapp_states (name, code) values('California',  'CA');
insert into mainapp_states (name, code) values('Colorado',  'CO');
insert into mainapp_states (name, code) values('Connecticut',  'CT');
insert into mainapp_states (name, code) values('Delaware',  'DE');
insert into mainapp_states (name, code) values('Florida',  'FL');
insert into mainapp_states (name, code) values('Georgia',  'GA');
insert into mainapp_states (name, code) values('Hawaii',  'HI');
insert into mainapp_states (name, code) values('Idaho',  'ID');
insert into mainapp_states (name, code) values('Illinois',  'IL');
insert into mainapp_states (name, code) values('Indiana',  'IN');
insert into mainapp_states (name, code) values('Iowa',  'IA');
insert into mainapp_states (name, code) values('Kansas',  'KS');
insert into mainapp_states (name, code) values('Kentucky',  'KY');
insert into mainapp_states (name, code) values('Louisiana',  'LA');
insert into mainapp_states (name, code) values('Maine',  'ME');
insert into mainapp_states (name, code) values('Maryland',  'MD');
insert into mainapp_states (name, code) values('Massachusetts',  'MA');
insert into mainapp_states (name, code) values('Michigan',  'MI');
insert into mainapp_states (name, code) values('Minnesota',  'MN');
insert into mainapp_states (name, code) values('Mississippi',  'MS');
insert into mainapp_states (name, code) values('Missouri',  'MO');
insert into mainapp_states (name, code) values('Montana',  'MT');
insert into mainapp_states (name, code) values('Nebraska',  'NE');
insert into mainapp_states (name, code) values('Nevada',  'NV');
insert into mainapp_states (name, code) values('New Hampshire',  'NH');
insert into mainapp_states (name, code) values('New Jerssy',  'NJ');
insert into mainapp_states (name, code) values('New Mexico',  'NM');
insert into mainapp_states (name, code) values('New York',  'NY');
insert into mainapp_states (name, code) values('North Carolina',  'NC');
insert into mainapp_states (name, code) values('North Dakota',  'ND');
insert into mainapp_states (name, code) values('Ohio',  'OH');
insert into mainapp_states (name, code) values('Oklahoma',  'OK');
insert into mainapp_states (name, code) values('Oregon',  'OR');
insert into mainapp_states (name, code) values('Pennsylvania',  'PA');
insert into mainapp_states (name, code) values('Rhode Island',  'RI');
insert into mainapp_states (name, code) values('South Carolina',  'SC');
insert into mainapp_states (name, code) values('South Dakota',  'SD');
insert into mainapp_states (name, code) values('Tennessee',  'TN');
insert into mainapp_states (name, code) values('Texas',  'TX');
insert into mainapp_states (name, code) values('Utah',  'UT');
insert into mainapp_states (name, code) values('Vermont',  'VT');
insert into mainapp_states (name, code) values('Virginia',  'VA');
insert into mainapp_states (name, code) values('Washington',  'WA');
insert into mainapp_states (name, code) values('West Virginia',  'WV');
insert into mainapp_states (name, code) values('Wisconsin',  'WI');
insert into mainapp_states (name, code) values('Wyoming',  'WY');
commit;